# Generated by Django 5.2.7 on 2025-10-19 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attraction',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('ARI', 'Aries'), ('TAU', 'Taurus'), ('GEM', 'Gemini'), ('CAN', 'Cancer'), ('LEO', 'Leo'), ('VIR', 'Virgo'), ('LIB', 'Libra'), ('SCO', 'Scorpio'), ('SAG', 'Sagittarius'), ('CAP', 'Capricorn'), ('AQU', 'Aquarius'), ('PIS', 'Pisces')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_matches', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
